FROM python:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /dockerdjangosetup
COPY requirements.txt /dockerdjangosetup/
RUN pip install -r requirements.txt
COPY . /dockerdjangosetup/