# Use the official Node.js image as the base image
FROM node:18.17.0-slim

# Set the working directory inside the container
WORKDIR /react-project

# Copy package.json and package-lock.json to the container
COPY package.json .

# Install dependencies
RUN npm install

# Copying all the files in our project
COPY . .

# Expose port 5173 for development server (not really necessary since it's handled by Docker Compose)
EXPOSE 5174

# Start the React development server with hot-reloading
CMD ["npm", "run", "dev"]