services:
  react-project-dev:
    container_name: react-project-container
    image: react-project-dev-image
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/react-project
      - /react-project/node_modules
    command: npm run dev
